site_name: PubZ - Publication Zoo
repo_url: https://github.com/getty708/PubZ
dev_addr: 127.0.0.1:7777
site_dir: ./site
theme:
  name: 'material'
markdown_extensions:
    - admonition
    - pymdownx.keys
    - codehilite
nav:
- Home: './index.md'
- About:
    - 'License': './license.md'
- Developer Guide:
    - 'Home': './dev/index-dev.md'
    - 'Models': './dev/models.md'
    - 'Dashboard': './dev/dashboard.md'
    - 'Registration': './dev/registration.md'
    - 'Notification': './dev/notification.md'
  
